# Autogenerated wrapper script for XGBoost_GPU_jll for x86_64-linux-gnu-cxx03-cuda+12.2
export libxgboost

using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("XGBoost_GPU")
JLLWrappers.@declare_library_product(libxgboost, "libxgboost.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libxgboost,
        "lib/libxgboost.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
